---
- name: Add key
  command: wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | apt-key add -

- name: Add repository
  command: echo deb http://dl.hhvm.com/ubuntu trusty main | tee /etc/apt/sources.list.d/hhvm.list

- name: Update sources
  apt: update_cache=yes

- name: Install HHVM
  npm: name={{ item }} global=yes
  with_items:
    - hhvm

- name: Configuration 1/
  lineinfile: dest=/etc/hhvm/server.ini line="hhvm.libxml.ext_entity_whitelist = file,http"

- name: Configuration 2/
  lineinfile: dest=/etc/hhvm/php.ini line="hhvm.libxml.ext_entity_whitelist = file,http"
  notify: restart hhvm
