---
- name: Add key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present

- name: Add repository
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu trusty main' state=present

- name: Update sources
  apt: update_cache=yes

- name: Install HHVM
  npm: name={{ item }} global=yes
  with_items:
    - hhvm

- name: Configuration 1/
  lineinfile: dest=/etc/hhvm/server.ini line="hhvm.libxml.ext_entity_whitelist = file,http"

- name: Configuration 2/
  lineinfile: dest=/etc/hhvm/php.ini line="hhvm.libxml.ext_entity_whitelist = file,http"
  notify: restart hhvm
