alias cdn='cd /usr/share/nginx/www'
alias cdnf='cd /usr/share/nginx/www/app'
alias u='phpunit -c app/'
alias sf='php app/console'

alias composer="hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer"