---
- name: Installing packages
  apt: name={{ item }} state=present
  with_items:
    - mc
    - unzip
    - git
    - python-pip
    - python-dev
    - libmysqlclient-dev
    - build-essential
    - software-properties-common
    - tmux
    - libsqlite3-dev
    - ruby1.9.1-dev

- name: Copy bash configuration
  copy: src=bashrc dest={{ item }}
  with_items:
    - "/home/vagrant/.bashrc"
    - "/root/.bashrc"

- name: Copy bash aliases
  copy: src=bash_aliases dest={{ item }}
  with_items:
    - "/home/vagrant/.bash_aliases"
    - "/root/.bash_aliases"

- name: Install gem packages
  gem: name=mailcatcher state=present user_install=no

- name: Copy mailcatcher configuration
  copy: src=mailcatcher.conf dest=/etc/init/mailcatcher.conf
  notify: start mailcatcher
