---
- name: Install MySQL
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - php5-mysql

- name: Install python mysql module
  pip: name=MySQL-python

- name: Copy MySQL config
  copy: src=my.cnf dest=/etc/mysql/my.cnf

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost

- name: remove the test database
  mysql_db: name=test state=absent

- name: Add app user
  mysql_user: name='app_db_user' password=123456 priv=*.*:ALL state=present

- name: Add the app database
  mysql_db: name=app_db state=present login_user=app_db_user login_password=123456
  notify: restart mysql

- name: Fetch latest version of PhpMyAdmin
  get_url: url=https://files.phpmyadmin.net/phpMyAdmin/4.4.15/phpMyAdmin-4.4.15-english.zip dest=/tmp validate_certs=false

- name: Unpack PhpMyAdmin
  unarchive: src=/tmp/phpMyAdmin-4.4.15-english.zip dest=/usr/share copy=no

- name: Rename
  command: mv /usr/share/phpMyAdmin-4.4.15-english /usr/share/phpmyadmin

- name: Create symling to the htdocs
  file: src=/usr/share/phpmyadmin dest=/usr/share/nginx/www/phpmyadmin state=link
  notify: restart nginx