---
- name: Adding python properties
  apt: name=python-software-properties state=present

- name: Adding PHP PPA
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present update_cache=yes

- name: Installing PHP 5.6
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php-pear
    - php5-cli
    - php5-intl
    - php5-mcrypt
    - php5-curl
    - php5-fpm
    - php5-memcached
    - memcached
    - php5-mysql
    - php5-sqlite
  notify: start memcached

- name: Configuration - php.ini
  copy: src=php.ini dest={{ item }}
  with_items:
    - "/etc/php5/fpm/php.ini"

- name: Configuration - php-fpm.conf
  copy: src=php-fpm.conf dest={{ item }}
  with_items:
    - "/etc/php5/fpm/php-fpm.conf"

- name: Configuration - www.conf
  copy: src=www.conf dest={{ item }}
  with_items:
    - "/etc/php5/fpm/pool.d/www.conf"

- name: Install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=555

- name: Move composer
  copy: src=composer.phar dest=/usr/local/bin/composer mode=555

- name: Install Phing (Add pear channel)
  command: pear channel-discover pear.phing.info
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Install Phing (Install package)
  command: pear install --alldeps phing/phing
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- include: qa.yml

- name: Build App
  command: phing chdir=/usr/share/nginx/www/app
  sudo: false
  ignore_errors: True
