---
- name: Adding python properties
  apt: name=python-software-properties state=present

- name: Adding PHP PPA
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present update_cache=yes

- name: Installing PHP 5.6
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php-pear
    - php5-cli
    - php5-intl
    - php5-mcrypt
    - php5-curl
    - php5-fpm
    - php5-memcached
    - php5-mysql
    - php5-sqlite

- name: Configuration 1/2
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^;date\.timezone =" line="date.timezone = 'Europe/Warsaw'"
  notify: restart php

- name: Configuration 2/2
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^;date\.timezone =" line="date.timezone = 'Europe/Warsaw'"

- name: Install composer
  get_url: url=https://getcomposer.org/download/1.0.0-alpha9/composer.phar dest=/usr/local/bin/composer mode=555

- include: qa.yml
