---
- name: Add repository
  command: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Installing package
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - build-essential

- name: Install global Node.js packages
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - gulp
