---
- name: Add repository
  apt_repository: repo='ppa:nginx/stable'

- name: Install Nginx
  apt: name=nginx state=present

- name: Copy main configuration file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy main host file
  copy: src=default.host dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Copy application host file (PHP)
  template: src=app.host dest=/etc/nginx/sites-available/app

- name: Copy application host file (HHVM)
  template: src=hhvm.host dest=/etc/nginx/sites-available/hhvm

- name: Enabling application vhost (PHP)
  file: src=/etc/nginx/sites-available/app dest=/etc/nginx/sites-enabled/app state=link

- name: Enabling application vhost (HHVM)
  file: src=/etc/nginx/sites-available/hhvm dest=/etc/nginx/sites-enabled/hhvm state=link
  notify: restart nginx