---
- name: Set up a development enviroment for symfony2
  hosts: all
  remote_user: vagrant
  sudo: true

  roles:
    - common
    - nginx
    - mysql
    - { role: nodejs, when: install_nodejs == true }
    - { role: hhvm, when: install_hhvm == true }
    - php