---
- name: Set up a development enviroment for symfony2
  hosts: all
  remote_user: vagrant
  sudo: true

  roles:
    - common
    - nginx
    - mysql
    - nodejs
    - { role: hhvm, when: intall_hhvm == true }
    - php